apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker-deployment
  labels:
    app: tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracker
  template:
    metadata:
      labels:
        app: tracker
    spec:
      nodeSelector:
        region: home
      containers:
        - name: tracker
          image: #{IMAGE}
          volumeMounts:
            - name: config
              mountPath: /app/etc
      volumes:
        - name: config
          configMap:
            name: tracker
