pipeline {
  agent any

  stages {
    stage("last-changes") {
      steps {
        script {
          def publisher = LastChanges.getLastChangesPublisher "PREVIOUS_REVISION", "SIDE", "LINE", true, true, "", "", "", "", ""
          publisher.publishLastChanges()
          def changes = publisher.getLastChanges()
          println(changes.getEscapedDiff())
          for (commit in changes.getCommits()) {
            println(commit)
            def commitInfo = commit.getCommitInfo()
            println(commitInfo)
            println(commitInfo.getCommitMessage())
            println(commit.getChanges())
          }
        }
      }
    }
  }
}