apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocean-deployment
  labels:
    app: ocean
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocean
  template:
    metadata:
      labels:
        app: ocean
    spec:
      nodeSelector:
        region: home
      containers:
        - name: ocean
          image: #{IMAGE}
          ports:
            - containerPort: 6666
              name: grpc
            - containerPort: 9101
              name: metrics
          volumeMounts:
            - name: config
              mountPath: /app/etc
      volumes:
        - name: config
          configMap:
            name: ocean
---
apiVersion: v1
kind: Service
metadata:
  name: ocean
spec:
  selector:
    app: ocean
  ports:
    - protocol: TCP
      port: 6666
      targetPort: grpc
      name: grpc
    - port: 9101
      targetPort: metrics
      name: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ocean
  labels:
    prom: home
spec:
  selector:
    matchLabels:
      app: ocean
  podMetricsEndpoints:
    - port: metrics