// Code generated by goctl. DO NOT EDIT!
// Source: ocean.proto

package server

import (
	"context"

	"dht-ocean/ocean/internal/logic/ocean"
	"dht-ocean/ocean/internal/svc"
	"dht-ocean/ocean/ocean"
)

type OceanServer struct {
	svcCtx *svc.ServiceContext
	ocean.UnimplementedOceanServer
}

func NewOceanServer(svcCtx *svc.ServiceContext) *OceanServer {
	return &OceanServer{
		svcCtx: svcCtx,
	}
}

func (s *OceanServer) IfInfoHashExists(ctx context.Context, in *ocean.IfInfoHashExistsRequest) (*ocean.IfInfoHashExistsResponse, error) {
	l := oceanlogic.NewIfInfoHashExistsLogic(ctx, s.svcCtx)
	return l.IfInfoHashExists(in)
}

func (s *OceanServer) CommitTorrent(ctx context.Context, in *ocean.CommitTorrentRequest) (*ocean.CommitTorrentResponse, error) {
	l := oceanlogic.NewCommitTorrentLogic(ctx, s.svcCtx)
	return l.CommitTorrent(in)
}
